### ISSUE TITLE
dxc dependency

### ISSUE THREAD

**Issue by VinnyVicious** [NVIDIAGameWorks/donut#13]
Is it possible to remove the dependency on dxc and rely on something free and open source?

**Comment by apanteleev** [comment]
Something free and open source, like what? [Glslang](https://github.com/KhronosGroup/glslang/)? It only generates SPIR-V and the language is inferior. [Slang](https://github.com/shader-slang/slang/) is open source, but it relies on DXC to generate DXIL too.

**Comment by VinnyVicious** [comment]
> and the language is inferior.
inferior how?

I would argue that relying on proprietary software that can go away at any moment at the core of your graphics pipeline is inferior than anything else.

**Comment by apanteleev** [comment]
> inferior how?

GLSL lacks many higher-level language features, such as: function overloading, namespaces, classes or structs with methods, implicit type casting, finally templates. Sure, you can live without them, but it gets more annoying the more complicated your shaders become.

Besides, DXC is actually an [open-source project](https://github.com/Microsoft/DirectXShaderCompiler/) that everyone uses, and it's not going away.

**Comment by VinnyVicious** [comment]
OK, understood!
