### ISSUE TITLE
git .modules

### ISSUE THREAD

**Issue by r2d2Proton** [NVIDIAGameWorks/donut#6]
Just a friendly note. I may be misusing git but it appears that submodules will not update unless you go the module folder and issue a checkout command. For example, if I clone the donut repo, I use the following commands

`git clone --recursive https://github.com/NVIDIAGameWorks/donut`
`CD donut`
`git submodule update --init --recursive`
`CD nvrhi`
`git checkout main`
`CD ..\thirdparty\imgui`
`git checkout master`
`CD ..\lz4`
`git checkout release`

Can someone confirm that the head is detached?
Also, how I should be updating the submodules with git?

![gitsubmoduleupdateinitrecursive](https://user-images.githubusercontent.com/4054178/217373485-9469bace-741d-4cb3-9c64-89c3bb51f976.png)

**Comment by r2d2Proton** [comment]
Based on Ivan's comment to use --recurse-submodules.

Either the command I am entering is wrong, or it doesn't work the way we think it does. Again, it could be my misunderstanding. As you may know, donut has a dependency on nvrhi. I added a small modification "Test" under Introduction to nvrhi::README.md:

`### Test`

And cloned the donut repo with:

`git clone --recursive https://github.com/r2d2Proton/donut`
`cd donut`
`git pull --recurse-submodules`

Notice in the first image below Test is missing. Also notice that the head is detached in nvrhi. In the second image, after the git checkout main, the current files is pulled from the repo. Am I doing something wrong?

![One 01](https://user-images.githubusercontent.com/4054178/217551907-ffc01b7b-2e82-45b6-a4f5-fb91e5fd7ac1.png)

![One 02](https://user-images.githubusercontent.com/4054178/217551959-adce8c79-4e44-436e-af88-983a21b9e1e0.png)

**Comment by apanteleev** [comment]
Git modules can be confusing, that's true. Explaining submodules is beyond the scope of this project or issue, but here's some article I found that may be helpful: https://gist.github.com/gitaarik/8735255

Closing.
