### ISSUE TITLE
 IBlob::IsEmpty() function naming is confusing

### ISSUE THREAD

**Issue by BlurryLight** [NVIDIAGameWorks/donut#9]
https://github.com/NVIDIAGameWorks/donut/blob/c67172ad14df7c60976ecd63c587cd9c15d208fa/include/donut/core/vfs/VFS.h#L63

It returns `True` when it is actually **NOT** empty, while other similar functions like `dm::box3::empty()` return `True` when empty or invalid.

**Comment by apanteleev** [comment]
Thank you for reporting this issue. Apparently, nobody has used the function before.

I fixed it and renamed the function to `isEmpty` to be more in-line with the other functions, and to prevent any code that might be using it from compiling without manual changes.
